service: gas-price-monitor-tool
frameworkVersion: '2'

custom:
  gasPriceBucketName: gas-price-bucket
  gasPriceDataFile: priceData
  gasDataUrl: https://www.gasum.com/yksityisille/tankkaa-kaasua/tankkaushinnat/
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  logRetentionInDays: 14
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - 'ses:SendEmail'
      Resource: '*'

  environment:
    gasPriceBucket: ${self:custom.gasPriceBucketName}
    gasPriceDataFile: ${self:custom.gasPriceDataFile}
    gasDataUrl: ${self:custom.gasDataUrl}

functions:
  MonitorTool:
    handler: index.handler
    events:
      - schedule: rate(6 hours)

resources:
  Resources:
    PriceBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.gasPriceBucketName}
        AccessControl: Private
